const UPDATE_CHOSEN = "game/UPDATE_CHOSEN";
const UPDATE_TOTAL_GAME = "game/UPDATE_TOTAL_GAME";
const RANDOM_GAME = "game/RANDOM_GAME"
const HANDLE_RESULT_GAME = "game/HANDLE_RESULT_GAME"
const PLAYING = "game/PLAYING"

export { UPDATE_CHOSEN, UPDATE_TOTAL_GAME, RANDOM_GAME, HANDLE_RESULT_GAME, PLAYING };